### ISSUE TITLE
VQA accuracy of StackNMN

### ISSUE THREAD

**Issue by j-min** [vardaan123/LNMN#1]
Hello, thanks for sharing the code.
While I was reading StackNMN paper and LNMN paper, I found the accuracy on VQA are differently reported. StackNMN has accuracy gap of around 10%.

From LNMN paper
![image](https://user-images.githubusercontent.com/18069263/91454837-643cfb80-e84f-11ea-8532-0222ed29a0fa.png)

From StackNMN paper
![image](https://user-images.githubusercontent.com/18069263/91454866-6b640980-e84f-11ea-8900-a1750e6acd8e.png)

Could you please explain how you obtained the VQA accuracy of these models?

**Comment by vardaan123** [comment]
Actually, the reported accuracy is for our own implementation of Stack-NMN by following the model equations as given in their paper. The code released by Stack-NMN has some inconsistency with what they have mentioned in their paper, so we didn't use that.
